sudo: false
language: node_js
cache:
  directories:
  - node_modules
before_script:
  - git config --global user.email $GH_EMAIL
  - git config --global user.name $GH_USERNAME
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  on:
    branch: master
