language: ruby
rvm:
  - 2.1.2
branches:
  only:
    - master
cache:
  bundler: true
notifications:
  email: false
before_script:
  - git config --global user.email $GH_EMAIL
  - git config --global user.name $GH_USERNAME
  - git remote add origin https://$GH_TOKEN@github.com/rowanhogan/rowanhogan.com.git
  - npm install -g bower
  - bower install -f
script:
  - bundle exec middleman deploy --build-before
global:
  env:
    secure: T8W4aVTL83K5ri0UCfwo1R4kFKHrZ8NWauDvbeOaoFM25ZJQD8VMOeH5LU1LwCj5Liy47BqU83iY7xgPBhY4durA6ihOtU54JTHtrvqbOG/9IlqPOyq2Rb7oSB3a6UAbbNizkXtH4REjk+AUrvhmVRndG38K+wo6c5NiJZ9Q5UM=
