language: ruby

rvm:
  - 2.1.2

branches:
  only:
    - master

cache:
  bundler: true

notifications:
  email: false

script:
  - 'npm install -g bower'
  - 'bower install -f'
  - 'git config --global user.email "test@example.com"'
  - 'git config --global user.name "Travis Build"'
  - "bundle exec middleman deploy --build-before"
