sudo: false
language: node_js
cache:
  directories:
  - node_modules
before_script:
  - git config --global user.email $GH_EMAIL
  - git config --global user.name $GH_USERNAME
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  local_dir: dist
  fqdn: rowanhogan.com
  verbose: true
  on:
    branch: master
